### ISSUE TITLE
Question Regarding Example

### ISSUE THREAD

**Issue by 4tuw2tuv0** [Z572/guile-wlroots#1]
First, thanks so much for writing this library (and the supporting ones).

I was trying out the example file you have and, when run, the screen becomes black.

I'm _assuming_ this is because, while a Wayland session is launched, no app.s or anything are so, of course, the screen is blank.

But, I guess, I just want to confirm if my suspicion is correct.

I still need to get an actual firm grasp on how `wlroots` works so the code in your example, at a high level, makes sense but I'm still uncertain of what much of it does (but thank you, a ton, for providing an example, at all; I tend to understand via examples so I wouldn't've begun to know where to start with your library, otherwise).

**Comment by Z572** [comment]
yes, if you don't render something, screen is black, 
for example: when scene-graph.scm running, you can run `WAYLAND_DISPLAY=wayland-1 emacs` at other terminal, will display emacs with screen, but cann't click it, because scene-graph.scm not handle input.

also can try https://github.com/Z572/guile-wlroots/blame/3be739b9e41603fcf4abc440d6cbf61083620ba9/example/red-window.scm.
will display a red screen, but cann't display any client,because not handled.

**Comment by 4tuw2tuv0** [comment]
Ahhhh; thank you! Part of my problem was I was calling this from a TTY (which then took over and, since it doesn't handle input, I couldn't get back to my desktop, any); I'd read, somewhere else, that'd be a problem and'd forgotten. I wasn't sure how to launch any programs in it, either, so that command is super helpful.

Oh, nice; I'll try that one out, as well. Thank you, again!
